name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install npm dependencies
        run: npm install && npm install -g editorconfig && npm install -g node-gyp
        

      - name: Install Python3
        run: sudo apt update
             sudo apt install -y python3
             echo "export PYTHON=$(which python3)" >> $GITHUB_ENV

      - name: Install another dependencies
        run: yarn install
             yarn serve
        
      - name: Cypress run
        uses: cypress-io/github-action@v6
        # after the test run completes store videos and any screenshots
      - uses: actions/upload-artifact@v4
      # add the line below to store screenshots only on failures
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`
      - uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`